### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ynohtna92** [ynohtna92/SheepTag#1]
Critical things that need to be completed. 
Upon completing a job mention this issue in your commit as well as checking off the task below.
- [x] Complete Farms
- [x] Complete Farm Abilities
- [ ] Add Custom Sounds / Music
- [x] Add in all shop items
- [x] Item Abilities
- [x] Update map to 7.7.4 (GridNav clearances etc)
- [x] Polish map (add props, textures, camera boundaries)
- [x] Add main game loop
- [x] Add in Wolves (Lycan)
- [x] Wolf Abilities
- [x] Add in Wisp (Sheep Spirit), and associated code for respawn/death etc
- [ ] Add in all text commands from 7.7.4
- [x] English Tooltips of all abilities/items/units/ui
- [x] Panorama Leaderboard
- [ ] Polish/Balance Game Mode
- [x] Workshop Image

**Comment by VincentK-ZA** [comment]
Hi there @ynohtna92 

I'm not at all experienced in custom games, but would like to make a small PR that allows using the shop regularly (i.e. right click to buy items). I think this broke somewhere along the line with some dota updates.

The simplest fix I could find was this:
```lua
GameRules:GetGameModeEntity():SetStashPurchasingDisabled(true)
```
to
```lua
GameRules:GetGameModeEntity():SetStashPurchasingDisabled(false)
```

Let me know how I can contribute the change here. If you do not have time or would prefer it, just let me know and I can create a fork and submit a new game if that is okay with you.
But would prefer to update yours.

Thank you for the awesome game that still works 99% after all these years!

**Comment by ynohtna92** [comment]
Hi @VincentK-ZA,

You should be able to create a branch, make the change and submit a pull request. I will approve it once I have confirmed it is all working.

**Comment by VincentK-ZA** [comment]
Thanks, but I don't have write access to the repository, so can't push my branch up.

This is the error I get when trying to push my branch up:
![image](https://user-images.githubusercontent.com/8651835/82318968-08054880-99d1-11ea-915e-0e6cb3fcc654.png)

**Comment by ynohtna92** [comment]
> Thanks, but I don't have write access to the repository, so can't push my branch up.
> 
> This is the error I get when trying to push my branch up:
> ![image](https://user-images.githubusercontent.com/8651835/82318968-08054880-99d1-11ea-915e-0e6cb3fcc654.png)

You will want to create a fork and do the change then make a pull request :).
